# Generated by Django 4.1.7 on 2023-02-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options_post_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='posts/', verbose_name='thumbnail'),
        ),
    ]
